### ISSUE TITLE
perplexity numbers

### ISSUE THREAD

**Issue by rabeehk** [madaan/minimal-text-diffusion#1]
Hi @madaan 
thanks for sharing your implementations, this is absolutely great and clean to follow it.
About the perplexity numbers reported in the github, I was wondering if you might have an intuition why they are higher than the original paper and if you could point me to the parts in implementation that are missing to make the results closer to the original work?
Many thanks.
Best
Rabeeh

**Comment by madaan** [comment]
Hi @rabeehk,

The perplexity was calculated by using an off-the-shelf model (`distilgpt2`) on a simplistic dataset created for demonstration/debugging (the dataset has been added [here](https://github.com/madaan/minimal-text-diffusion/tree/main/data), [eval script](https://github.com/madaan/minimal-text-diffusion/blob/main/src/utils/eval_ppl.py)).

One of the biggest missing pieces was controllable generation. I've just finished a classifier-guided implementation ([details](https://github.com/madaan/minimal-text-diffusion/blob/main/docs/controllable.md)), which appears to be working on this simple dataset. The next big TODOs for me are to add some more documentation around the working of the model, and running the code on a different dataset (perhaps Yelp reviews?).

**Comment by rabeeh-karimi** [comment]
Hi Aman,
 thank you for the helpful response.
Given that the best perplexity is for random initialization, Is the given checkpoint provided for the setting of `MODEL_PT-True_EMBEDS_PT-True-FREEZE_EMBEDS-False` ?
Many thanks.

**Comment by madaan** [comment]
Hi Rabeeh,

Thanks for trying this out!

> MODEL_PT-False_EMBEDS_PT-False-FREEZE_EMBEDS-False
Should be the right checkpoint for random initialization (model pre-trained False, embeddings False, and train embeddings True). I should probably find better names for these.

In my recent experiments, I find that word-level tokenization + starting from scratch (no pre-training) works best. The checkpoint is in `ckpts/simplev2`, with links and some more details here: https://github.com/madaan/minimal-text-diffusion/blob/main/docs/controllable.md.

**Comment by rabeehk** [comment]
Hi @madaan 
thank you.
Best
Rabeeh
