### ISSUE TITLE
Google Drive Checkpoint folder is Empty

### ISSUE THREAD

**Issue by Elfsong** [madaan/minimal-text-diffusion#10]
The Google Drive Checkpoint folder provided in your readme is Empty. Could you check it? Thank you!

**Comment by bansky-cl** [comment]
I want to download this too but it is empty.

**Comment by madaan** [comment]
Sorry, I think I had the wrong permissions on the drive so someone end up deleting the checkpoint. Does this work: https://drive.google.com/drive/folders/1zPiopN0MqhkYNlUza6zOChPqWyoDofLh?usp=sharing?

**Comment by Elfsong** [comment]
Thank you! It works.
