### ISSUE TITLE
Multiplt GPU acceleration

### ISSUE THREAD

**Issue by yuanenming** [madaan/minimal-text-diffusion#2]
Hi @madaan 
thanks for sharing your implementations, it is really helpful and very clean to follow. 

I met some problems when trying to use multiple GPUs.
I find that simply changing the visible devices to like `0,1,2,3` in the `run_train.sh` scripts dose not help.
I am not familiar with the mpi4py package. So could you please tell me the way to use multiple GPUs with minimal modifications?

Thanks in advance.

**Comment by yuanenming** [comment]
Hi, I solved it with reference to improve diffusion

**Comment by madaan** [comment]
Thanks @yuanenming ! It will be great if you could share your fix here in case others face the same issue.

**Comment by yuanenming** [comment]
Sure, like follows:
```
mpiexec -n $NUM_GPUS python scripts/run_train.py
```
Simply add the `mpiexec` command
