### ISSUE TITLE
Import errors & Problems in gaussian_diffusion.py

### ISSUE THREAD

**Issue by mainpyp** [madaan/minimal-text-diffusion#5]
Hi @madaan, 
first of all thank you for this very nice curated repository. 😊 I am currently trying to train my own diffusion language model and for that I am trying to follow your [greetings datasets tutorial](https://github.com/mainpyp/prot-minimal-text-diffusion/blob/main/docs/training_on_your_own_dataset.md): 

I got it running however I encountered 2 problems that I want to mention here:
1. In **train.py**: importing train_infer and modules within the src directory was not working. What then worked for me was adding src.train_infer within the file and adding the repositories directory to the PYTHONPATH with `export PYTHONPATH=<full_path_to_repo>:$PYTHONPATH`
2.  In **gaussian_diffusion.py**: In line [246](https://github1s.com/madaan/minimal-text-diffusion/blob/HEAD/src/modeling/diffusion/gaussian_diffusion.py#L246) and line [259](https://github1s.com/madaan/minimal-text-diffusion/blob/HEAD/src/modeling/diffusion/gaussian_diffusion.py#259) the module attribute of model.model is called. However that raised an AttributeError for me. Removing .module from both calls fixed the problem. 

Am I missing something here or did you encountered a similar problem?

**Comment by madaan** [comment]
Hey,

I did not face these issues!

Where are you running the command from?

From the top directory, can you try setting:

```sh
export PYTHONPATH=".:../:.:src"
``` 

and please try again?

**Comment by mainpyp** [comment]
@madaan that also worked! Thank you very much and sorry for the delayed reply!

**Comment by mainpyp** [comment]
This fixes the src module issue as well, however the error from the gaussian_diffusion import remains. Which version of python are you using for your environment since I am convinced that I have some dependency problems within my environment!

**Comment by mainpyp** [comment]
This fixes the src module issue as well, however the error from the gaussian_diffusion import remains. Which version of python are you using for your environment since I am convinced that I have some dependency problems within my environment!

**Comment by mainpyp** [comment]
The error was that I set the GPU number to 1 and  CUDA_VISIBLE_DEVICES (that starts with 0 and I only have one gpu) is called with that.
Using `bash scripts/run_train.sh greetings 0 False False False 5000` worked for me. However I still don't understand the error message.

**Comment by mainpyp** [comment]
Addition: 
I ran into similar issues because the dependencies are not correct at least for me. 
What worked was: 
1. create a conda env with python 3.8 
`conda create -n diffusion python=3.8`
2. then install requirements.txt with pip
`pip install -r requirements.txt` (updated requirements down below)
3. last install these packages with conda 
`conda install mpi4py`
`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
`conda install -c conda-forge pytorch-gpu pympler`
`conda install -c huggingface transformers`


My requirements.txt file (optionally added pympler):
*blobfile == 1.3.3
boto3 == 1.24.85
botocore == 1.27.85
ftfy == 6.1.1
huggingface_hub==0.4.0
numpy == 1.23.1
pandas == 1.5.0
regex == 2022.9.11
requests == 2.28.1
sacremoses == 0.0.53
sentencepiece == 0.1.97
six == 1.16.0
spacy == 3.2.4
tokenizers == 0.12.1
tqdm == 4.49.0
transformers == 4.21.3
wandb == 0.13.3
pympler*
