### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by ostov-larion** [madaan/minimal-text-diffusion#6]
I trying run it on colab, but it fell with this error:
```
Traceback (most recent call last):
  File "src/train_infer/train.py", line 13, in <module>
    from src.utils import dist_util, logger
ModuleNotFoundError: No module named 'src'
```

**Comment by madaan** [comment]
Thanks! Can you please mention how did you solve the problem? I think others will benefit a lot from it.

**Comment by kaustubholpadkar** [comment]
To solve this, one needs to add 'src' folder in python path as follows:
`export PYTHONPATH="${PYTHONPATH}:/path/to/src/"`
